PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
INSERT {
  GRAPH ?ocmwG {
    ?persoon ?p ?o.
  }
} WHERE {
  GRAPH ?ocmwG {
    ?verkiezing ext:copiedForOCMW ?ocmw.
    ?lijst mandaat:behoortTot ?verkiezing.
    ?res mandaat:isResultaatVoor ?lijst.
    ?res mandaat:isResultaatVan ?persoon.
  }
  ?persoon ?p ?o.
}