PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX org: <http://www.w3.org/ns/org#>

# Process nb members gemeenteraad
DELETE {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatVoorzitter ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "gemeenteraad".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatLid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000011>.
    OPTIONAL {
      ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    }
    ?mandaatVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000012>.
    OPTIONAL {
      ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}

# Process nb members cbs
DELETE {
  GRAPH ?graph {
    ?mandaatSchepen ext:minAantalHouders ?huidigMinSchepen;
        ext:maxAantalHouders ?huidigMaxSchepen.
    ?mandaatBurgemeester ext:minAantalHouders ?huidigMinBurgemeester;
        ext:maxAantalHouders ?huidigMaxBurgemeester.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatSchepen ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatBurgemeester ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
    ?mandaatAangewezenBurgemeester ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "schepenen".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatSchepen org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000014>.
    OPTIONAL {
      ?mandaatSchepen ext:minAantalHouders ?huidigMinSchepen;
        ext:maxAantalHouders ?huidigMaxSchepen.
    }
    ?mandaatBurgemeester org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000013>.
    OPTIONAL {
      ?mandaatBurgemeester ext:minAantalHouders ?huidigMinBurgemeester;
        ext:maxAantalHouders ?huidigMaxBurgemeester.
    }
    ?mandaatAangewezenBurgemeester org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/7b038cc40bba10bec833ecfe6f15bc7a>.
    OPTIONAL {
      ?mandaat mandaatAangewezenBurgemeester ext:minAantalHouders ?huidigMinAangewezenBurgemeester;
        ext:maxAantalHouders ?huidigMaxAangewezenBurgemeester.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}

# Process nb members RMW
DELETE {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatVoorzitter ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "rmw".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatLid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000015>.
    OPTIONAL {
      ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    }
    ?mandaatVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000016>.
    OPTIONAL {
      ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}

# Process nb members BCSD
DELETE {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatVoorzitter ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "bcsd".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatLid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000019>.
    OPTIONAL {
      ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    }
    ?mandaatVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001a>.
    OPTIONAL {
      ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}

# Process nb members Vast Bureau
DELETE {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatVoorzitter ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "vast bureau".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatLid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000017>.
    OPTIONAL {
      ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    }
    ?mandaatVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000018>.
    OPTIONAL {
      ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}

# Process nb members Districtsraad
DELETE {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
  }
}
INSERT {
  GRAPH ?graph {
    ?mandaatLid ext:minAantalHouders ?min;
        ext:maxAantalHouders ?max.
    ?mandaatVoorzitter ext:minAantalHouders 1;
        ext:maxAantalHouders 1.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp/load> {
    ?row a ext:NbMembersObject;
         ext:bestuurseenheid ?naam1;
         ext:leden_max ?max;
         ext:leden_min ?min;
         ext:mandaat "districtraad".
    FILTER (isNumeric(?max) && isNumeric(?min))
  }
  GRAPH ?g {
    ?bestuurseenheid a besluit:Bestuurseenheid;
      skos:prefLabel ?naam2;
      besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000003>.
    ?bestuursperiode a ext:Bestuursperiode;
      skos:prefLabel "2025 - heden".
  }
  GRAPH ?h {
    ?bestuursorgaan a besluit:Bestuursorgaan;
      besluit:bestuurt ?bestuurseenheid;
      ^mandaat:isTijdspecialisatieVan ?bestuursorgaanIT.
    ?bestuursorgaanIT ext:heeftBestuursperiode ?bestuursperiode;
      org:hasPost ?mandaat.
    ?mandaatLid org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001b>.
    OPTIONAL {
      ?mandaatLid ext:minAantalHouders ?huidigMinLid;
        ext:maxAantalHouders ?huidigMaxLid.
    }
    ?mandaatVoorzitter org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e00001c>.
    OPTIONAL {
      ?mandaatVoorzitter ext:minAantalHouders ?huidigMinVoorzitter;
        ext:maxAantalHouders ?huidigMaxVoorzitter.
    }
  }
  BIND (?h AS ?graph)
  FILTER (LCASE(STR(REPLACE(?naam1, "\\s+$", ""))) = LCASE(STR(REPLACE(?naam2, "\\s+$", ""))))
}