PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
      ?s mu:uuid """f5c28f23-c664-42ec-b840-7af42ea855a3""". 
  }
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/bestuursorganen/f5c28f23-c664-42ec-b840-7af42ea855a3> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT ((COUNT (DISTINCT ?uuid)) AS ?count) WHERE {
    GRAPH <http://mu.semte.ch/application> {
    <http://data.lblod.info/id/bestuursorganen/f5c28f23-c664-42ec-b840-7af42ea855a3> org:hasPost ?resource. ?resource mu:uuid ?uuid;           a ?class. VALUES ?class {mandaat:Mandaat}. 
  }
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT DISTINCT ?uuid WHERE {
    GRAPH <http://mu.semte.ch/application> {
    <http://data.lblod.info/id/bestuursorganen/f5c28f23-c664-42ec-b840-7af42ea855a3> org:hasPost ?resource. ?resource mu:uuid ?uuid;           a ?class. VALUES ?class {mandaat:Mandaat}. 
  }
} GROUP BY ?uuid OFFSET 0 LIMIT 20

CONSTRUCT {

} WHERE {

}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
      ?s mu:uuid """be3b86e6-222e-43a4-b29c-2b75c422ac84""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/be3b86e6-222e-43a4-b29c-2b75c422ac84> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """2af3085e-baba-4f38-ac21-166bb5d72819""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/2af3085e-baba-4f38-ac21-166bb5d72819> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
CONSTRUCT { 
  ?source <http://mu.semte.ch/ext/pred2> ?var2.
  ?source <http://mu.semte.ch/ext/pred1> ?var1.
  ?source <http://mu.semte.ch/ext/pred0> ?var0.

} WHERE {VALUES ?source { <http://data.lblod.info/id/mandaten/2af3085e-baba-4f38-ac21-166bb5d72819> <http://data.lblod.info/id/mandaten/be3b86e6-222e-43a4-b29c-2b75c422ac84> }
 
{  ?source ext:maxAantalHouders ?var2.
}
UNION
{  ?source ext:minAantalHouders ?var1.
}
UNION
{  ?source mandaat:aantalHouders ?var0.
}
}