PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """75c51c04fe18067f56b8327affb07e0dac7e2890f90b23d2e72d2979946854ba""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/bestuursorganen/75c51c04fe18067f56b8327affb07e0dac7e2890f90b23d2e72d2979946854ba> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT ((COUNT (DISTINCT ?uuid)) AS ?count) WHERE {
    GRAPH <http://mu.semte.ch/application> {
    <http://data.lblod.info/id/bestuursorganen/75c51c04fe18067f56b8327affb07e0dac7e2890f90b23d2e72d2979946854ba> org:hasPost ?resource. ?resource mu:uuid ?uuid;           a ?class. VALUES ?class {mandaat:Mandaat}. 
}
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
SELECT DISTINCT ?uuid WHERE {
    GRAPH <http://mu.semte.ch/application> {
    <http://data.lblod.info/id/bestuursorganen/75c51c04fe18067f56b8327affb07e0dac7e2890f90b23d2e72d2979946854ba> org:hasPost ?resource. ?resource mu:uuid ?uuid;           a ?class. VALUES ?class {mandaat:Mandaat}. 
}
} GROUP BY ?uuid OFFSET 0 LIMIT 20

CONSTRUCT {

} WHERE {

}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """bb21988c8cad8130f873bf8b96297fae4b15a2a1412dab0305741f1330b0048e""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/bb21988c8cad8130f873bf8b96297fae4b15a2a1412dab0305741f1330b0048e> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """5b64281e1504c4842d71050f9fc4ad29672c895baa6c105eb7b3455ba79b130a""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/5b64281e1504c4842d71050f9fc4ad29672c895baa6c105eb7b3455ba79b130a> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """c4b1999f8257c07ad1c20e6bd0a86eb1c8c20fee34c662ad3b7e62090e698ff5""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/c4b1999f8257c07ad1c20e6bd0a86eb1c8c20fee34c662ad3b7e62090e698ff5> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
SELECT ?s WHERE {
    GRAPH <http://mu.semte.ch/application> {
    ?s mu:uuid """32b6865210208632ed8d2f59233c7399c09c42455388d51713b97ffeb1f6b704""". 
}
}

SELECT DISTINCT ?target WHERE {
    <http://data.lblod.info/id/mandaten/32b6865210208632ed8d2f59233c7399c09c42455388d51713b97ffeb1f6b704> a ?target.
}

PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
CONSTRUCT { 
  ?source <http://mu.semte.ch/ext/pred2> ?var2.
  ?source <http://mu.semte.ch/ext/pred1> ?var1.
  ?source <http://mu.semte.ch/ext/pred0> ?var0.

} WHERE {VALUES ?source { <http://data.lblod.info/id/mandaten/32b6865210208632ed8d2f59233c7399c09c42455388d51713b97ffeb1f6b704> <http://data.lblod.info/id/mandaten/c4b1999f8257c07ad1c20e6bd0a86eb1c8c20fee34c662ad3b7e62090e698ff5> <http://data.lblod.info/id/mandaten/5b64281e1504c4842d71050f9fc4ad29672c895baa6c105eb7b3455ba79b130a> <http://data.lblod.info/id/mandaten/bb21988c8cad8130f873bf8b96297fae4b15a2a1412dab0305741f1330b0048e> }
 
{  ?source ext:maxAantalHouders ?var2.
}
UNION
{  ?source ext:minAantalHouders ?var1.
}
UNION
{  ?source mandaat:aantalHouders ?var0.
}
}
