PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX bestuursperiode: <http://data.lblod.info/id/concept/Bestuursperiode/>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX extlmb:  <http://mu.semte.ch/vocabularies/ext/lmb/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?boi mandaat:bindingStart ?bindingStart .
    ?boi dct:modified ?modified .
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?boi mandaat:bindingStart ?earliestStart .
    ?boi dct:modified ?now .
  }
}
WHERE {
  ?bestuursorgaan besluit:classificatie / skos:inScheme extlmb:gemeente-bestuursorgaan-codes .

  ?boi mandaat:isTijdspecialisatieVan ?bestuursorgaan .
  ?boi lmb:heeftBestuursperiode ?periode .
  ?boi org:hasPost ?mandaat .

  GRAPH <http://mu.semte.ch/graphs/public> {
    OPTIONAL {
      ?boi mandaat:bindingStart ?bindingStart .
    }
  }
  OPTIONAL {
    ?boi dct:modified ?modified .
  }
  {{
    SELECT DISTINCT ?boi (MIN(?start) AS ?earliestStart) 
    WHERE {
      ?boi org:hasPost ?mandaat .
      GRAPH ?g {
        ?mandataris org:holds ?mandaat .
        ?mandataris mandaat:start ?start .
      }
      ?g ext:ownedBy ?bestuurseenheid .
    } GROUP BY ?boi ?earliestStart
  }}
  BIND(NOW() AS ?now)
}
