PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ivs: <http://data.lblod.info/id/concept/InstallatievergaderingStatus/>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX bestuursperiode: <http://data.lblod.info/id/concept/Bestuursperiode/>

INSERT {
  GRAPH ?g {
    ?installatievergadering a lmb:Installatievergadering;
      mu:uuid ?uuid;
      lmb:hasStatus ivs:b54dbe98-d618-4af7-9f01-791aa90774e4;
      lmb:heeftBestuurseenheid ?bestuurseenheid;
      lmb:heeftBestuursperiode bestuursperiode:96efb929-5d83-48fa-bfbb-b98dfb1180c7.
  }
}
WHERE {
  ?bestuurseenheid a besluit:Bestuurseenheid;
      besluit:classificatie ?classificatie;
      mu:uuid ?bestuurseenheidId.

  FILTER (?classificatie IN (<http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000002>))

  BIND(STRUUID() AS ?uuid)
  BIND(IRI(CONCAT("http://data.lblod.info/id/installatievergaderingen/", STR(?uuid))) AS ?installatievergadering).
  BIND(IRI(CONCAT("http://mu.semte.ch/graphs/organizations/", STR(?bestuurseenheidId), "/LoketLB-mandaatGebruiker")) AS ?g).
}
