PREFIX org: <http://www.w3.org/ns/org#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?mandataris mandaat:start ?startDate .
    ?mandataris dcterms:modified ?modified .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris mandaat:start ?oldestStartDate .
    ?mandataris dcterms:modified ?now .
  }
}
WHERE {
  {
    SELECT DISTINCT ?mandataris ?g (MIN(?schepenStartDate) AS ?oldestStartDate)
    WHERE {
      GRAPH ?g {
        VALUES ?mandataris {
          <http://data.lblod.info/id/mandatarissen/67234993AE5F6D098DC007ED>
          <http://data.lblod.info/id/mandatarissen/672E1CE5D456831DB328892A>
          <http://data.lblod.info/id/mandatarissen/67349878F5EE8564CFAD9B85>
          <http://data.lblod.info/id/mandatarissen/673B47ADBE4A66FE75F1DD0D>
          <http://data.lblod.info/id/mandatarissen/672A2640A12BA678FC887469>
          <http://data.lblod.info/id/mandatarissen/673DA1DBFA0EDA29ED949B2D>
          <http://data.lblod.info/id/mandatarissen/67488AC575F41FD3A91CDAF7>
          <http://data.lblod.info/id/mandatarissen/6721E76FFDAA900F9C5408BE>
          <http://data.lblod.info/id/mandatarissen/67335EFAD2F339806D122628>
          <http://data.lblod.info/id/mandatarissen/672A4999BB97C1379BFE1338>
        }

        ?mandataris org:holds ?mandaat . 
        ?mandataris mandaat:start ?startDate .
        OPTIONAL {  
          ?mandataris dcterms:modified ?modified .
        }

        ?boi org:hasPost ?mandaat .
        ?boi lmb:heeftBestuursperiode <http://data.lblod.info/id/concept/Bestuursperiode/96efb929-5d83-48fa-bfbb-b98dfb1180c7> . # 2024 - heden

        ?schepenMandaat org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000014> . # Schepen
        ?boi org:hasPost ?schepenMandaat .

        ?schepenMandataris org:holds ?schepenMandaat . 
        ?schepenMandataris mandaat:start ?schepenStartDate .
      }
      ?g ext:ownedBy ?someone .
    }
    GROUP BY ?mandataris ?g
  }
  BIND(NOW() as ?now)
}
