PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dct: <http://purl.org/dc/terms/>
DELETE {
  GRAPH ?g {
    ?mandataris mandaat:start ?start .
    ?mandataris dct:modified ?oldModified .
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris dct:modified ?now .
  }
}
WHERE {
  GRAPH ?g {
    ?mandataris a mandaat:Mandataris ;
      mandaat:start ?start ;
      dct:modified ?oldModified .
  }
  BIND(NOW() AS ?now)
  VALUES (?mandataris ?start) {
    (<http://data.lblod.info/id/mandatarissen/a42a5194-1059-4d36-b69d-0216d076d0b7> "2024-12-05T00:00:00"^^xsd:dateTime)
    (<http://data.lblod.info/id/mandatarissen/5dfb3796-c5d1-4c5a-a398-ce31eba16999> "2024-12-05T00:00:00"^^xsd:dateTime)
    (<http://data.lblod.info/id/mandatarissen/dd8e9e6f-e843-4418-a963-8e4f75019df0> "2024-12-05T00:00:00"^^xsd:dateTime)
    (<http://data.lblod.info/id/mandatarissen/3404e976-8aaa-4154-be80-b0200e8805ff> "2024-12-05T00:00:00"^^xsd:dateTime)
    (<http://data.lblod.info/id/mandatarissen/13b613b5-664b-4b7b-88cc-0518d9c62973> "2024-12-05T00:00:00"^^xsd:dateTime)
    (<http://data.lblod.info/id/mandatarissen/fac56a27-0a0a-429c-9649-22c1696114cd> "2024-12-05T00:00:00"^^xsd:dateTime)
  }
}