PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://lblod.data.gift/display-types/lmb/custom-codelist-input> a ext:DisplayType ;
     mu:uuid "db2c1748-3f68-461b-8093-43b94ae58777" ;
     skos:prefLabel "Codelijst" .

    <http://lblod.data.gift/display-types/lmb/custom-codelist-input> skos:inScheme <http://lblod.data.gift/concept-schemes/lmb-custom-display-types> .

    <http://data.lblod.info/id/lmb/form-library-entries/7dd17cb0-ce73-4ccb-b6d3-f7723a85f083> a ext:FormLibraryEntry ;
      mu:uuid "7dd17cb0-ce73-4ccb-b6d3-f7723a85f083" ;
      sh:name "Nationaliteit" ;
      form:displayType <http://lblod.data.gift/display-types/lmb/custom-codelist-input> ;
      sh:path <https://data.vlaanderen.be/ns/persoon#heeftNationaliteit> ;
      sh:order 1000 .

    <http://data.lblod.info/id/lmb/form-library-entries/8991472a-db3f-4f61-b070-5da7883be37d> a ext:FormLibraryEntry ;
      mu:uuid "8991472a-db3f-4f61-b070-5da7883be37d" ;
      sh:name "Telefoonnummer" ;
      form:displayType <http://lblod.data.gift/display-types/lmb/custom-string-input> ;
      sh:path <http://schema.org/telephone> ;
      sh:order 1000 .
  }
}