PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX astreams: <http://www.w3.org/ns/activitystreams#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
DELETE {
  GRAPH ?g {
    ?mandataris ?p ?o.
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris a astreams:Tombstone.
    ?mandataris dct:modified ?now .
    ?mandataris astreams:deleted ?now .
    ?mandataris astreams:formerType mandaat:Mandataris.
  }
}
WHERE {
  VALUES ?mandataris {
    <http://data.lblod.info/id/mandatarissen/048881DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048881F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04888202-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04888203-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF25-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF10-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF24-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891E9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF57-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF6B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AF6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AD8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AEC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AE2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AED-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891E92-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EA6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EA7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EBA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EBB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890B01-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890B00-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/b8a415d2-8742-42ba-932f-474c204a6128>
    <http://data.lblod.info/id/mandatarissen/04895D3B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D58-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D1C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D30-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D59-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BE2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D62-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BE3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D6C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D6D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BD8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1824-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A182E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A136A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1356-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17FC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1806-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1807-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1810-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A181A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A182F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1838-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17F2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69F0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A181B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E1A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69F1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69FA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A6A04-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAA8C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAB4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAA0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAAA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF884-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF870-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB784-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0112-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B011C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB78E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B011D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0126-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB78F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB798-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB7A2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00EA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0108-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0127-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0130-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B013A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B013B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF88E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF898-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B4212-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B6FC6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B6FD0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACA3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACAC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACB6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACB7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACC0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BA70C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BA720-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC8F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACA2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4FA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4B4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4C8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4F0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4F1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF504-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF505-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF50E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D24-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D39-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4DD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40E0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4109-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40F5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4108-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D10-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D1A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA33C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D25-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D57-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D6B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA350-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA351-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA365-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA36E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA378-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA382-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C9D74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C9D60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED4D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED61-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA379-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CEA90-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048D2596-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048D25AA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/652E426496FC0E4DDF39B174>
    <http://data.lblod.info/id/mandatarissen/5C34C6C69E5B640009000E8C>
    <http://data.lblod.info/id/mandatarissen/5C360ABE9E5B640009000395>
    <http://data.lblod.info/id/mandatarissen/5C360CC09E5B6400090003A3>
    <http://data.lblod.info/id/mandatarissen/5C387D7A57753A000A0000B4>
    <http://data.lblod.info/id/mandatarissen/6111152EB7632D0008000178>
    <http://data.lblod.info/id/mandatarissen/5C3F18DF57753A00090006AC>
    <http://data.lblod.info/id/mandatarissen/6620CA37AA69EC8A8A9E00FF>
    <http://data.lblod.info/id/mandatarissen/5C9CDDB8D5BECA00090002B3>
    <http://data.lblod.info/id/mandatarissen/5C9CDE7DD5BECA00090002B5>
    <http://data.lblod.info/id/mandatarissen/5E9593EEA3ACB600080001CB>
    <http://data.lblod.info/id/mandatarissen/5F744D9F6111420008000723>
    <http://data.lblod.info/id/mandatarissen/5E284F47A3ACB60008000440>
    <http://data.lblod.info/id/mandatarissen/5F915096CE511800080003DD>
    <http://data.lblod.info/id/mandatarissen/0493F967-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F97A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F894-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C8C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F95C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F966-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C97-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F970-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CAB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CB4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CBF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CD3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C6E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C83-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C96-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CA0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CAA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CBE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CC8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CD2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C82-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2A8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2B2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CDC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E62-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E6C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E58-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E6D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E59-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1AE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1EA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7AE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E790-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7A5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7A4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F190-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F19A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1AF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1B8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1C2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1C3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1CC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1D7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1A4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1E0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535BB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/6580b7bc-b524-4f55-842a-b52b6ee0e9aa>
    <http://data.lblod.info/id/mandatarissen/04953C54-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04953C5E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C580E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5868-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5872-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5873-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C8734-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C8748-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA75-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA7E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7EE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7F9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC802-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC80C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC80D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA88-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA89-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C5E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C68-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C72-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C90-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C9A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0CA4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D04E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D04D4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C7C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C7D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C86-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C91-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4534-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D786A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4548-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4549-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4552-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D455C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D7888-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D455D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4566-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D7874-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D787E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA420-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA42A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA434-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA43E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD300-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD314-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD9FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DDA08-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F2C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F36-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F40-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F4A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BA4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BB9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BC2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BCD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BD6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BE0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E553C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5528-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BB8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BCC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC365-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC36E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC378-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED41C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED41D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED426-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED431-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED43A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED444-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC382-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC379-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED412-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22BE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED430-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED445-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED44E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22C8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22DD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F5748-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F573E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F5752-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F575C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F575D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB422-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB436-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB441-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB440-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD3C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD46-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD50-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD5B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD64-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD6E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD6F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD78-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD82-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD83-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD47-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD5A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007A7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007BB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007C4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007EC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A00788-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A00792-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0079C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007B0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007CE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007D8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007E2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05468-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05472-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05454-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0545E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D00-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D0A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D15-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007CF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D28-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007E3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D29-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D32-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C48-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05CF6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D14-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D1E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C5D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A90E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A918-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A922-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A92C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2D4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2E9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2F2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB31-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB1C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB30-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A12E9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A12EB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1765E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17672-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1861C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1332E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A13338-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1769A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17686-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1767C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17673-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17687-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17690-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A185F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A185FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18608-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18612-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18626-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18631-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1863A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1864E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1CE74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1CE60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6B2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18630-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18644-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A206D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A206E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23076-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23080-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2308A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23094-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23095-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2309E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A27BBC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A27BD0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F038-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F04C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F056-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F061-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F060-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FA9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAA6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAB1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FABA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAC5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FACE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B3E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B52-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B85-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372C5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372C4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B34-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B48-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B53-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B67-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B99-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBAC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBC0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBCA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBCB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBD4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBDE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A40216-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A40202-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44410-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44406-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4441A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A443FC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D85-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D99-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44DA2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49078-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49082-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4976C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49780-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4908C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5123C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51250-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51251-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5125A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51264-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51265-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A54D9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A54D88-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A552A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5772C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57736-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57740-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5774A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5774B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57754-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEF2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEE8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7F9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D802-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D80C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D816-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D820-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEFC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CF06-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D80D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A60C64-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A60C6E-DCC6-11EF-BC01-8152F78DE954>
  }
  GRAPH ?g {
    ?mandataris ?p ?o.
  }
  ?g ext:ownedBy ?someone.
  BIND(NOW() AS ?now)
};
DELETE {
  GRAPH ?g {
    ?o ?p ?mandataris .
  }
} WHERE {
  VALUES ?mandataris {
    <http://data.lblod.info/id/mandatarissen/048881DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048881F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04888202-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04888203-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF25-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF10-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF24-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891E9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF57-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF6B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0488BF74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AF6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AD8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AEC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AE2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AED-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890AC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891E92-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EA6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EA7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EBA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EBB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04891EC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890B01-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04890B00-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/b8a415d2-8742-42ba-932f-474c204a6128>
    <http://data.lblod.info/id/mandatarissen/04895D3B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D58-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D1C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D30-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D59-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BE2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D62-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BE3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D6C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04895D6D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04899BD8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1824-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A182E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A136A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1356-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17FC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1806-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1807-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1810-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A181A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A182F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A1838-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A17F2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69F0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A181B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A5E1A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69F1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A69FA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048A6A04-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAA8C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAB4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAA0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AAAAA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF884-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF870-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB784-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0112-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B011C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB78E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B011D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0126-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB78F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB798-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AB7A2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00EA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B00FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0108-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0127-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B0130-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B013A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B013B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF88E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048AF898-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B4212-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B6FC6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048B6FD0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACA3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACAC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACB6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACB7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACC0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BA70C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BA720-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BAC8F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BACA2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4FA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4B4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4C8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4F0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4F1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF504-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF505-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF50E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D24-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D39-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048BF4DD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40E0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4109-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40F5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4108-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C40F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D10-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D1A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA33C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D25-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D2E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D43-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D57-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C4D6B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA350-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA351-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA365-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA36E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA378-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA382-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C9D74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048C9D60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED38-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED42-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED4C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED4D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED56-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED61-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CA379-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CED6A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048CEA90-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048D2596-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/048D25AA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/652E426496FC0E4DDF39B174>
    <http://data.lblod.info/id/mandatarissen/5C34C6C69E5B640009000E8C>
    <http://data.lblod.info/id/mandatarissen/5C360ABE9E5B640009000395>
    <http://data.lblod.info/id/mandatarissen/5C360CC09E5B6400090003A3>
    <http://data.lblod.info/id/mandatarissen/5C387D7A57753A000A0000B4>
    <http://data.lblod.info/id/mandatarissen/6111152EB7632D0008000178>
    <http://data.lblod.info/id/mandatarissen/5C3F18DF57753A00090006AC>
    <http://data.lblod.info/id/mandatarissen/6620CA37AA69EC8A8A9E00FF>
    <http://data.lblod.info/id/mandatarissen/5C9CDDB8D5BECA00090002B3>
    <http://data.lblod.info/id/mandatarissen/5C9CDE7DD5BECA00090002B5>
    <http://data.lblod.info/id/mandatarissen/5E9593EEA3ACB600080001CB>
    <http://data.lblod.info/id/mandatarissen/5F744D9F6111420008000723>
    <http://data.lblod.info/id/mandatarissen/5E284F47A3ACB60008000440>
    <http://data.lblod.info/id/mandatarissen/5F915096CE511800080003DD>
    <http://data.lblod.info/id/mandatarissen/0493F967-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F97A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F894-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C8C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F95C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F966-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C97-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0493F970-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CAB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CB4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CBF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CD3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C6E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C83-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C96-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CA0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CAA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CBE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CC8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CD2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943C82-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2A8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2B2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04943CDC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E62-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E6C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E58-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E6D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04948E59-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1AE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494A2DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1EA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7AE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E790-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7A5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494E7A4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F190-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F19A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1AF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1B8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1C2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1C3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1CC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1D7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1A4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/0494F1E0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535BB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049535A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/6580b7bc-b524-4f55-842a-b52b6ee0e9aa>
    <http://data.lblod.info/id/mandatarissen/04953C54-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04953C5E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C580E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5868-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5872-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C5873-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C8734-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049C8748-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA75-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA7E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7EE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC7F9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC802-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC80C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CC80D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA88-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049CBA89-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C5E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C68-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C72-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C90-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C9A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0CA4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D04E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D04D4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C7C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C7D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C86-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D0C91-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4534-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D786A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4548-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4549-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4552-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D455C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D7888-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D455D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D4566-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D7874-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049D787E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA420-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA42A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA434-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DA43E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD300-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD314-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DD9FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049DDA08-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F2C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F36-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F40-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E1F4A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BA4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BB9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BC2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BCD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BD6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BE0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E553C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5528-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BB8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E5BCC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049E8F7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC365-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC36E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC378-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED41C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED41D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED426-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED431-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED43A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED444-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC382-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049EC379-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED412-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22BE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED430-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22DC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED445-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049ED44E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22C8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22DD-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F22E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F5748-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F573E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F5752-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F575C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049F575D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB422-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB436-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB441-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FB440-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD3C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD46-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD50-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD5B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD64-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD6E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD6F-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD78-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD82-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD83-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD47-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/049FBD5A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007A7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007BB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007C4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007EC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A00788-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A00792-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0079C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007B0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007CE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007D8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007E2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05468-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05472-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05454-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0545E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D00-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D0A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D15-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007CF-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D28-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A007E3-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D29-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D32-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C48-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05CF6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D14-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A05D1E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C5D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A09C70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A90E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A918-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A922-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0A92C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2E8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2D4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2E9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0E2F2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB26-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB31-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB3A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB44-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB1C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB30-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB45-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A0EB4E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A12E9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A12EB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1765E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17672-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1861C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1332E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A13338-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1769A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17686-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1767C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17673-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17687-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A17690-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A185F4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A185FE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18608-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18612-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18626-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18631-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1863A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1864E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1CE74-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1CE60-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6B2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18630-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A18644-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A1D6E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A206D2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A206E6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23076-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23080-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2308A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23094-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A23095-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2309E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A27BBC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A27BD0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F038-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F04C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F056-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F061-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2F060-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FA9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAA6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAB0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAB1-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FABA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAC4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FAC5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A2FACE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372BA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B3E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B52-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B5C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B71-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B85-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372C5-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A372C4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B34-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B48-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B53-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B67-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A37B99-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBAC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBC0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBCA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBCB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBD4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A3CBDE-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406BC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406C7-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A40216-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A40202-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406C6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406D0-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406DA-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A406DB-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44410-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44406-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4441A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A443FC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D66-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D70-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D7A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D84-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D85-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D8E-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D98-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44D99-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A44DA2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49078-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49082-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4976C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A49780-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A4908C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5123C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51250-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51251-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5125A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51264-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A51265-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A54D9C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A54D88-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A552A6-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5772C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57736-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57740-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5774A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5774B-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A57754-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEF2-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEE8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A346-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7F8-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7F9-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D802-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D80C-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A35A-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5A364-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D816-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D820-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CEFC-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5CF06-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D7E4-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A5D80D-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A60C64-DCC6-11EF-BC01-8152F78DE954>
    <http://data.lblod.info/id/mandatarissen/04A60C6E-DCC6-11EF-BC01-8152F78DE954>
  }
  GRAPH ?g {
    ?o ?p ?mandataris.
  }
}