PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dcterms: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g { 
    ?boit mandaat:bindingEinde ?einde.
    ?boit dcterms:modified ?modified.
  }
}
INSERT {
  GRAPH ?g { 
    ?boit mandaat:bindingEinde """2024-12-15T23:00:00Z"""^^xsd:dateTime.
    ?boit dcterms:modified ?now.
  }
}
WHERE {
  GRAPH ?g {
    ?boit mandaat:bindingEinde ?einde.
    ?boit mandaat:bindingStart """2019-01-01"""^^xsd:date.
    OPTIONAL {
      ?boit dcterms:modified ?modified.
    }
  }
  ?g ext:ownedBy ?blankenberge.
  FILTER(?blankenberge IN(
    <http://data.lblod.info/id/bestuurseenheden/6377f53f54990033c90de6101e263f4d9e41eb7c3e4f70dec48caccefc253760>, # Gemeente Blankenberge
    <http://data.lblod.info/id/bestuurseenheden/56061c5a09c4e4fab34edffa2585bd47b5c104edea687e409a9a926b2197850d> # OCMW Blankenberge
  ))
  BIND(NOW() as ?now)
} 
