  PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
  PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
  PREFIX prov: <http://www.w3.org/ns/prov#>
  PREFIX org: <http://www.w3.org/ns/org#>
  PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
  PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
  PREFIX eli: <http://data.europa.eu/eli/ontology#>
  
  DELETE {
    GRAPH ?gRechtsgrond {
     ?rechtsgrond ?gp ?go .
    }
  }
  INSERT {
    GRAPH ?gRechtsgrond {
      ?newRechtsgrond a eli:LegalResource .
      ?newRechtsgrond mandaat:bekrachtigtAanstellingVan ?mandataris .
      ?newRechtsgrond prov:wasDerivedFrom ?newLink .
      ?newRechtsgrond ext:isAddedThroughMigration true .
    }
  }
  WHERE {
    GRAPH ?g {
      ?mandataris a mandaat:Mandataris .
      ?mandataris mandaat:start """2024-12-01T23:00:00Z"""^^xsd:dateTime .
      ?mandataris org:holds ?mandaat .
    }
    ?boi org:hasPost ?mandaat .
    ?boi mandaat:isTijdspecialisatieVan ?bestuursorgaan .
    ?bestuursorgaan besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000005> . # Gemeenteraad
    ?g ext:ownedBy <http://data.lblod.info/id/bestuurseenheden/393a7495daffabe3dabd5d341673287cedc58485c3c8bc273cbd058e735dfee2> . # Gemeente Gavere

    VALUES (?newRechtsgrond ?newLink) {
      (
       <https://gavere-echo.cipalschaubroeck.be/id/besluiten/4e1d83d3-7a38-425b-81f2-619141a5a286> # Generated id
       """https://gavere-echo.cipalschaubroeck.be/raadpleegomgeving/zittingen/c5912094-829e-496c-8b70-eab84b2a3af7/besluitenlijst"""
       )
    }
    GRAPH ?gRechtsgrond {
      ?rechtsgrond mandaat:bekrachtigtAanstellingVan|mandaat:bekrachtigtOntslagVan ?mandataris .
      ?rechtsgrond ?gp ?go .
    }
  }
