PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX dct: <http://purl.org/dc/terms/>
DELETE {
  GRAPH ?g {
    ?mandataris mandaat:einde ?end.
    ?mandataris dct:modified ?mod.
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris mandaat:einde ?newEnd.
    ?mandataris dct:modified ?now.
  }
}
WHERE {
  GRAPH ?g {
    ?mandaat a mandaat:Mandaat.
    ?orgInT org:hasPost ?mandaat.
    ?mandataris org:holds ?mandaat.
    ?mandataris dct:modified ?mod.

    ?mandataris mandaat:einde ?end.
    FILTER(?mod > "2024-01-01T00:00:00Z"^^xsd:dateTime)
  }
  ?g ext:ownedBy ?someone.
  BIND(bif:dateadd('day', 1, xsd:DateTime(?end)) AS ?newEnd)
  BIND(NOW() AS ?now)
} 