PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX form: <http://lblod.data.gift/vocabularies/forms/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/lmb/form-library-entries/8991472a-db3f-4f61-b070-5da7883be37d> a ext:FormLibraryEntry ;
      mu:uuid "8991472a-db3f-4f61-b070-5da7883be37d" ;
      sh:name "Telefoonnummer" ;
      form:displayType <http://lblod.data.gift/display-types/lmb/custom-string-input> ;
      sh:path <http://schema.org/telephone> ;
      sh:order 1000 ;
      form:validatedBy <http://data.lblod.info/id/lmb/custom-forms/validation/valid-phone-number>.

    <http://data.lblod.info/id/lmb/custom-forms/validation/valid-phone-number> a form:ValidPhoneNumber;
      form:defaultCountry "BE";
      form:grouping form:MatchEvery.
  }
}