  PREFIX dct: <http://purl.org/dc/terms/>
  PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

  DELETE {
    GRAPH ?h {
      ?s dct:modified ?other.
    }
  }
  INSERT {
    GRAPH ?h {
      ?s dct:modified ?oldest.
    }
  }
  WHERE {
    GRAPH ?g {
      ?s dct:modified ?oldest.
    }
    GRAPH ?h {
      ?s dct:modified ?other.
    }
    FILTER NOT EXISTS {
      ?s dct:modified ?evenOlder.
      FILTER(?evenOlder > ?oldest)
    }
    ?g ext:ownedBy ?someone.
    ?h ext:ownedBy ?someoneElse.

    FILTER (?oldest > ?other)
  }