PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX dcterms: <http://purl.org/dc/terms/>

  DELETE {
    GRAPH ?g {
      <http://data.lblod.info/id/mandatarissen/6735C20E0AE786390B4DB9AF> dcterms:modified ?modified.
    }
  }
  INSERT {
    GRAPH ?g {
      <http://data.lblod.info/id/mandatarissen/6735C20E0AE786390B4DB9AF> mandaat:isBestuurlijkeAliasVan ?now.
    }
  }
  WHERE {
    GRAPH ?g {
      <http://data.lblod.info/id/mandatarissen/6735C20E0AE786390B4DB9AF> mandaat:isBestuurlijkeAliasVan <http://data.lblod.info/id/personen/31d28cce-0f1b-482f-96eb-9723084f4694> . # Koen Veulemans
      <http://data.lblod.info/id/mandatarissen/6735C20E0AE786390B4DB9AF> dcterms:modified ?modified.
    }
    BIND(NOW() as ?now)
    BIND(<http://mu.semte.ch/graphs/organizations/c1c28cd9e31c25100374482b71b951d5be9b849454b1bd7e1a5158a589bda5de/LoketLB-mandaatGebruiker> AS ?g)
  }
