PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?as {
    ?persoon foaf:familyName "Bruggemans".
  }
}
INSERT {
  GRAPH ?as {
    ?persoon foaf:familyName "Bruggeman".
  }
}
WHERE {
  BIND (<http://mu.semte.ch/graphs/organizations/c2c19bec2f337e69a4c9838eacd88041734db523df4f7534cf407c9d380b64b8/LoketLB-mandaatGebruiker> AS ?as)
  GRAPH ?as {
    ?persoon a person:Person.
    ?persoon persoon:gebruikteVoornaam """Jill""".
    ?persoon foaf:familyName "Bruggemans".
  }
}