PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>

INSERT {
	GRAPH ?g {
		?iv ?p ?o.
	}
}
WHERE {
	GRAPH <http://mu.semte.ch/graph/temp/load> {
		?iv a ext:Installatievergadering.
		?iv ext:hasBestuursorgaanInDeTijd ?bestuursorgaanInTijd.
		?iv ?p ?o.
	}

	GRAPH ?g {
		?bestuursorgaanInTijd mandaat:isTijdspecialisatieVan ?bestuursorgaan.
	}
}
