PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/9acb3807-1bb9-4454-b323-636ca092ef30> persoon:gebruikteVoornaam ?firstName.
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/9acb3807-1bb9-4454-b323-636ca092ef30> persoon:gebruikteVoornaam """Dirk""".
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/9acb3807-1bb9-4454-b323-636ca092ef30> persoon:gebruikteVoornaam ?firstName.
  }
}
