  PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
  PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
  PREFIX dcterms: <http://purl.org/dc/terms/>
  PREFIX astreams: <http://www.w3.org/ns/activitystreams#>
  PREFIX org: <http://www.w3.org/ns/org#>

  DELETE {
    GRAPH <http://mu.semte.ch/graphs/organizations/856cbc8af3fbe7390d43420e249c288596e87fbc069c601751d5c5fcd52c543b/LoketLB-mandaatGebruiker> {
      ?mandataris ?p ?o.
    }
  }
  INSERT {
    GRAPH <http://mu.semte.ch/graphs/organizations/856cbc8af3fbe7390d43420e249c288596e87fbc069c601751d5c5fcd52c543b/LoketLB-mandaatGebruiker> {
      ?mandataris a astreams:Tombstone.
      ?mandataris dcterms:modified ?now .
      ?mandataris astreams:deleted ?now .
      ?mandataris astreams:formerType mandaat:Mandataris.

      ?membership a astreams:Tombstone.
      ?membership dcterms:modified ?now .
      ?membership astreams:deleted ?now .
      ?membership astreams:formerType org:Membership .
    }
  }
 WHERE {
    VALUES (?mandataris ?persoon) {
      # Samenstelling Gemeenteraad Denderleeuw
      ( <http://data.lblod.info/id/mandatarissen/f32c1ee8-a0de-4e42-9071-fbd6cae2ec41> <http://data.lblod.info/id/personen/cb298756-ac14-4a8e-a2ce-fd7f12fefa0d> ) # Marleen - Van der Hoeven
      ( <http://data.lblod.info/id/mandatarissen/9011d284-f7f6-427b-80d4-f4ad74f48fdf> <http://data.lblod.info/id/personen/9804b66931f5acffd982fffe0fc1fd1721f1ea1d3a87125e6630ed5ed3f62d16> ) # Pierre - Boschmans
      ( <http://data.lblod.info/id/mandatarissen/2ddd7637-4ee8-41cc-b3a6-09ce62de6b5e> <http://data.lblod.info/id/personen/b0ce5759-a33b-413f-971b-99fc1c830279> ) # Katia - Sonck
      ( <http://data.lblod.info/id/mandatarissen/82a5e685-f1fc-4b77-823e-e6798e46acbb> <http://data.lblod.info/id/personen/84010037f2f7df0459b0b58a87933a2577eeca3426a68c7756f5207538042059> ) # Joris - Vercammen
      ( <http://data.lblod.info/id/mandatarissen/d747c7d7-71cd-4af3-bc20-3e6b32973867> <http://data.lblod.info/id/personen/84010037f2f7df0459b0b58a87933a2577eeca3426a68c7756f5207538042059> ) # Joris - Vercammen
      ( <http://data.lblod.info/id/mandatarissen/2a2a05a2-0e5c-40db-a282-a24084f40684> <http://data.lblod.info/id/personen/9f41176d-59e4-4a1a-a77e-953c28382a84> ) # Brent - Van de Winckel
      ( <http://data.lblod.info/id/mandatarissen/4ce5150c-8abd-47cd-a591-37023ed16bc7> <http://data.lblod.info/id/personen/079a77526135628ff778e9d1a1d5efe9e5073a0d46abc76e12820ed07de22461> ) # Ingrid - Temmerman
      ( <http://data.lblod.info/id/mandatarissen/01c52041-5ad0-44b8-ace0-9e199140da14> <http://data.lblod.info/id/personen/d0718c59a8d56ef1f9e6ee82b5478e7f45b1a7241cf1d5212f2b47dd37c657ad> ) # Jan - De Nul
      ( <http://data.lblod.info/id/mandatarissen/b113cdf1-fae3-497d-84a1-bbb6b8af9a1c> <http://data.lblod.info/id/personen/3b4692bf-e5aa-4a74-8c70-7f1fb18e663e> ) # Chancelvie - Okitokandjo
      ( <http://data.lblod.info/id/mandatarissen/300ab513-47c1-4bd0-8e9f-c0d16d76d289> <http://data.lblod.info/id/personen/5036d6fc-7689-4814-a76b-5d8f76e85b3b> ) # Jochen - Baert
      ( <http://data.lblod.info/id/mandatarissen/fd06c501-848b-4fa0-a5b5-54c9d56567bc> <http://data.lblod.info/id/personen/f418356900e53a2c8f31b4bfed41106c31b04b971cf848bad715e2e8987dcd08> ) # Christel - De Bruecker
      ( <http://data.lblod.info/id/mandatarissen/1ca7f25b-4197-44a1-aaad-9299f86b2a0a> <http://data.lblod.info/id/personen/7c0c0e90-0459-40a2-a6e8-aa7b110297f2> ) # Jonas - Cosyns
      ( <http://data.lblod.info/id/mandatarissen/da47fc14-5d84-410b-8422-8649ecfc42b0> <http://data.lblod.info/id/personen/f65accfce0f8d29ffc80b171a7b4eb43dc556b1b58a0c2da38d9ac656c88024f> ) # Erna - Scheerlinck
      ( <http://data.lblod.info/id/mandatarissen/b1d9be19-182e-47b9-91c9-8f2f19633809> <http://data.lblod.info/id/personen/bb1d87ff15870b5e8238c31e52d4915833c3880fe35415bfade055d2224b39cf> ) # Kristof - Slagmulder
      # Samenstelling Raad voor Maatschappelijk Welzijn Denderleeuw
      ( <http://data.lblod.info/id/mandatarissen/e8ddfcbb-b942-458e-86f2-01d0af6877fc> <http://data.lblod.info/id/personen/e0830e0d7de4dc38df0f29267a173a23b9def2ee5e4a9c19f31d04e510d70f42> ) # Sofie - Renders
      ( <http://data.lblod.info/id/mandatarissen/73f943dc-6eca-4817-939c-20db10cac5dd> <http://data.lblod.info/id/personen/71402ada-9eb4-4ea0-8b03-65542fe9db9e> ) # Ekanga Olivier - Kungambolo
      # Samenstelling College van Burgemeester en Schepenen Denderleeuw
      ( <http://data.lblod.info/id/mandatarissen/eff229ca-b021-49f5-97a7-36ff949f4f05> <http://data.lblod.info/id/personen/3b4692bf-e5aa-4a74-8c70-7f1fb18e663e> ) # Chancelvie - Okitokandjo
      ( <http://data.lblod.info/id/mandatarissen/53482b56-848b-4e8f-a18b-f4bd348d7b88> <http://data.lblod.info/id/personen/af09a92e521b3833dabc64d901cf62b66b4d653a2b381fe023a559b3bd754a5d> ) # Yves - De Smet
      # Samenstelling Vast Bureau Denderleeuw
      ( <http://data.lblod.info/id/mandatarissen/8e590c0d-8016-473f-b990-c03bd7197e5a> <http://data.lblod.info/id/personen/af09a92e521b3833dabc64d901cf62b66b4d653a2b381fe023a559b3bd754a5d> ) # Yves - De Smet
      ( <http://data.lblod.info/id/mandatarissen/5ff1bac1-ba64-4a82-91a0-c8d9c72fa5f0> <http://data.lblod.info/id/personen/3b4692bf-e5aa-4a74-8c70-7f1fb18e663e> ) # Chancelvie - Okitokandjo # 2026!!
    }

      GRAPH <http://mu.semte.ch/graphs/organizations/856cbc8af3fbe7390d43420e249c288596e87fbc069c601751d5c5fcd52c543b/LoketLB-mandaatGebruiker> {
      ?mandataris mandaat:isBestuurlijkeAliasVan ?persoon.
      ?mandataris org:hasMembership ?membership.
      ?mandataris ?p ?o.
      OPTIONAL {
        ?mandataris dcterms:modified ?modified.
      }
    }
    BIND(NOW() AS ?now)
  }