PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?bertem {
    ?persoon persoon:gebruikteVoornaam """Joel""".
  }
}
INSERT {
  GRAPH ?bertem {
    ?persoon persoon:gebruikteVoornaam """Joël""".
  }
}
WHERE {
  BIND (<http://mu.semte.ch/graphs/organizations/7c44225c68f7535a603d3a0a0c57a6424e8baa9fd066b6b9baa636d0facddb72/LoketLB-mandaatGebruiker> AS ?bertem)
  GRAPH ?bertem {
    ?persoon a person:Person.
    ?persoon persoon:gebruikteVoornaam """Joel""".
    ?persoon foaf:familyName "Vander Elst".
  }
}