PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
INSERT {
	GRAPH ?g {
		?s ?p ?o
	}
}
WHERE {
	GRAPH <http://mu.semte.ch/graph/temp/load> {
		?s ext:wasInGraph ?g.
		?s ?p ?o.
		FILTER (?p != ext:wasInGraph)
	}
}
