PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/837f22280b0fe5ddb16b02ac13b842045fab931c59f9b4a7bba31bf5446e4f76> persoon:gebruikteVoornaam ?firstName.
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/837f22280b0fe5ddb16b02ac13b842045fab931c59f9b4a7bba31bf5446e4f76> persoon:gebruikteVoornaam """Agnes""".
  }
}
 WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/837f22280b0fe5ddb16b02ac13b842045fab931c59f9b4a7bba31bf5446e4f76> persoon:gebruikteVoornaam ?firstName.
  }
}