PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX astreams: <http://www.w3.org/ns/activitystreams#>

DELETE {
  GRAPH ?g {
    ?old ?p ?o.
  }
}
INSERT {
  GRAPH ?g {
    ?old owl:sameAs ?new.
    ?old a astreams:Tombstone.
    ?old astreams:delated ?now.
    ?old dct:modified ?now.
    ?old astreams:formerType <http://data.vlaanderen.be/ns/mandaat#Fractie>.
  }
}
WHERE {
  VALUES (?old ?new) {
    ( <http://data.lblod.info/id/fracties/670F6F17337218FF843C7BBE> <http://data.lblod.info/id/fracties/671B4CF00C2BDDC757010367> )
  }
  GRAPH ?g {
    ?old ?p ?o.
  }
  BIND(NOW() as ?now)
}