PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?herkDeStad {
    <http://data.lblod.info/id/personen/177d33d4-8610-4f47-9a27-980c721c0725> persoon:geslacht ?female.
  }
}
INSERT {
  GRAPH ?herkDeStad {
    <http://data.lblod.info/id/personen/177d33d4-8610-4f47-9a27-980c721c0725> persoon:geslacht  <http://publications.europa.eu/resource/authority/human-sex/MALE>.
  }
}
WHERE {
  BIND (<http://mu.semte.ch/graphs/organizations/a9e63c13a602de3cc5463cc81eee0b8d80d14a1846d1deb82b3a2d4e7efc96af/LoketLB-mandaatGebruiker> AS ?herkDeStad)
  GRAPH ?herkDeStad {
    <http://data.lblod.info/id/personen/177d33d4-8610-4f47-9a27-980c721c0725> persoon:geslacht ?female.
  }
}