PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX astreams: <http://www.w3.org/ns/activitystreams#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH ?g {
    ?geb ?p ?o.
    <http://data.lblod.info/id/personen/bf4316a60f3fb1c6625300d1ee94be08e59459e8c19bfae91fd9ed0a858616f1> persoon:heeftGeboorte ?geb .
  }
}
INSERT {
  GRAPH ?g {
    ?geb a astreams:Tombstone.
    ?geb dct:modified "2024-10-28T06:40:38.258Z"^^xsd:dateTime .
    ?geb astreams:deleted "2024-10-28T06:40:38.258Z"^^xsd:dateTime .
    ?geb astreams:formerType persoon:Geboorte .
    ?geb owl:sameAs <http://data.lblod.info/id/geboorte/23b934b6-9569-4c88-a763-27611b823edc> .
  }
} WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/bf4316a60f3fb1c6625300d1ee94be08e59459e8c19bfae91fd9ed0a858616f1> persoon:heeftGeboorte ?geb .
    ?geb ?p ?o.
  }
  FILTER (?geb != <http://data.lblod.info/id/geboorte/23b934b6-9569-4c88-a763-27611b823edc>)
}
