PREFIX conceptscheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s skos:inScheme conceptscheme:BeleidsdomeinCode;
       skos:topConceptOf conceptscheme:BeleidsdomeinCode.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s a ext:BeleidsdomeinCode;
       a skos:Concept.
  }
}