PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/36dc5fe0b7995220160e5ccce9309fd1c3bbbb56ff03c470f6a7d9a0e0aa94c7> persoon:gebruikteVoornaam """Joel""".
  }
}
INSERT {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/36dc5fe0b7995220160e5ccce9309fd1c3bbbb56ff03c470f6a7d9a0e0aa94c7> persoon:gebruikteVoornaam """Joël""".
  }
}
WHERE {
  GRAPH ?g {
    <http://data.lblod.info/id/personen/36dc5fe0b7995220160e5ccce9309fd1c3bbbb56ff03c470f6a7d9a0e0aa94c7> persoon:gebruikteVoornaam """Joel""".
  }
}