PREFIX person: <http://www.w3.org/ns/person#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

DELETE {
  GRAPH ?gemeenteAs {
    <http://data.lblod.info/id/personen/c900c042-e4ef-4e13-94a8-b5b66f47fd83> foaf:familyName ?familyName.
  }
}
INSERT {
  GRAPH ?gemeenteAs {
    <http://data.lblod.info/id/personen/c900c042-e4ef-4e13-94a8-b5b66f47fd83> foaf:familyName "Bruggeman".
  }
}
WHERE {
  BIND (<http://mu.semte.ch/graphs/organizations/c2c19bec2f337e69a4c9838eacd88041734db523df4f7534cf407c9d380b64b8/LoketLB-mandaatGebruiker> AS ?gemeenteAs)
  GRAPH ?gemeenteAs {
    <http://data.lblod.info/id/personen/c900c042-e4ef-4e13-94a8-b5b66f47fd83> foaf:familyName ?familyName.
  }
}