PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

DELETE {
	GRAPH <http://mu.semte.ch/graphs/public> {
		?beleid ?p ?o.
	}
}
WHERE {
	GRAPH <http://mu.semte.ch/graphs/public> {
		?beleid a ext:BeleidsdomeinCode.
		?beleid ?p ?o.
	}
}
