PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE {
  GRAPH ?g { 
    ?boit mandaat:bindingEinde ?einde.
  }
}
INSERT {
  GRAPH ?g { 
    ?boit mandaat:bindingEinde """2024-12-02"""^^xsd:date.
  }
}
WHERE {
  GRAPH ?g {
    ?boit mandaat:isTijdspecialisatieVan ?bo.
    ?boit mandaat:bindingEinde ?einde.
    ?boit mandaat:bindingStart """2019-01-01"""^^xsd:date.
  }
  ?g ext:ownedBy ?something.
} 
