PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX astreams: <http://www.w3.org/ns/activitystreams#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  GRAPH ?g {
    ?mandataris ?p ?o.
    ?membership ?memberP ?memberO.
  }
}
INSERT {
  GRAPH ?g {
    ?mandataris a astreams:Tombstone.
    ?mandataris dct:modified ?now .
    ?mandataris astreams:deleted ?now .
    ?mandataris astreams:formerType mandaat:Mandataris .

    ?membership a astreams:Tombstone.
    ?membership dct:modified ?now .
    ?membership astreams:deleted ?now .
    ?membership astreams:formerType org:Membership .
  }
}
WHERE {
  GRAPH ?g {
    VALUES ?ocmw {
      <http://data.lblod.info/id/bestuurseenheden/76730bd9ab6808230335d90e9ff30ad362a3461ee0239fd978e4313bcdca44c5> # Sint-Genesius-Rode
      <http://data.lblod.info/id/bestuurseenheden/0b5d1664b3cf08550bcfdac0f4b195ab7a46a0f1974726de864dc0edb1565ecc> # Linkebeek
      <http://data.lblod.info/id/bestuurseenheden/9ba66c8f97bbc6dd3ba2b35d8a6bb79215facbe3e5b3d52672b785449d6f5e58> # Drogenbos
      <http://data.lblod.info/id/bestuurseenheden/7f2c5143806d6110feb44eba2a91d58e8fd563465b94d0f6b40d13a6a1740940> # Wemmel
      <http://data.lblod.info/id/bestuurseenheden/45f432ac38d124141638c62f7afd577ab847c3571061b45e3b0b3329f6194048> # Kraainem
      <http://data.lblod.info/id/bestuurseenheden/f9ee0b69624bba3677b18b95110246ee9106377c948ab5d914909eac79f88bcf> # Wezembeek-Oppem
    }
    ?boi lmb:heeftBestuursperiode <http://data.lblod.info/id/concept/Bestuursperiode/96efb929-5d83-48fa-bfbb-b98dfb1180c7> . # 2024 - heden
    ?boi mandaat:isTijdspecialisatieVan ?bestuursorgaan.
    ?boi org:hasPost ?mandaat.

    ?bestuursorgaan besluit:classificatie <http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5ab0e9b8a3b2ca7c5e000009>. # BCSD
    ?bestuursorgaan besluit:bestuurt ?ocmw.

    ?mandataris org:holds ?mandaat.
    ?mandataris org:hasMembership ?membership.
    ?mandataris ?p ?o.
    ?membership ?memberP ?memberO.
  }
  ?g ext:ownedBy ?something .
  BIND(NOW() as ?now)
}
