  PREFIX dct: <http://purl.org/dc/terms/>
  PREFIX owl: <http://www.w3.org/2002/07/owl#>
  DELETE {
    GRAPH ?g {
      <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> dct:modified ?old.
      <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> ?p ?o.
    }
    GRAPH ?h {
      ?oo ?pp <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> .
      ?oo dct:modified ?oldOther.
    }
  }
  INSERT {
    GRAPH ?g {
      <http://data.lblod.info/id/personen/0bd64b06-c6ef-41e7-97ea-45bf1b4cef63> ?p ?o.
      <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> owl:sameAs <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968>.
      <http://data.lblod.info/id/personen/0bd64b06-c6ef-41e7-97ea-45bf1b4cef63> dct:modified ?now.
    }
    GRAPH ?h {
      ?oo ?pp <http://data.lblod.info/id/personen/0bd64b06-c6ef-41e7-97ea-45bf1b4cef63> .
      ?oo dct:modified ?now.
    }
  }WHERE {
    GRAPH ?g {
      <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> ?p ?o.
      FILTER(?p NOT IN (<http://data.vlaanderen.be/ns/persoon#gebruikteVoornaam>, <http://xmlns.com/foaf/0.1/familyName>))
      OPTIONAL {
        <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968> dct:modified ?old.
      }
    }
    OPTIONAL {
      GRAPH ?h {
        ?oo ?pp <http://data.lblod.info/id/personen/6630925FF0F686D7CD7EF968>.
        OPTIONAL {
          ?oo dct:modified ?oldOther.
        }
      }
    }
    BIND(NOW() AS ?now)
  }