PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX regorg: <http://www.w3.org/ns/regorg#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT ?s ?p ?o WHERE {
  # Werkingsgebieden
  {
    GRAPH <http://mu.semte.ch/graphs/tmp> {
      ?s a prov:Location ;
        ?p ?o .
      FILTER (?p IN (mu:uuid, rdf:type, rdfs:label, ext:werkingsgebiedNiveau))
    }
  }
  UNION
  # Bestuurseenheden
  {
    GRAPH <http://mu.semte.ch/graphs/tmp> {
      ?s a besluit:Bestuurseenheid ;
        ?p ?o .
      FILTER (?p IN (mu:uuid, rdf:type, skos:prefLabel, besluit:werkingsgebied, org:classification, org:linkedTo))
    }
  }
  UNION
  # Bestuursorganen
  {
    GRAPH <http://mu.semte.ch/graphs/tmp> {
      ?s a besluit:Bestuursorgaan ;
        ?p ?o .
      FILTER (?p IN (mu:uuid, rdf:type, skos:prefLabel, besluit:bestuurt, org:classification))
      FILTER NOT EXISTS { ?bestuursorgaan generiek:isTijdsspecialisatieVan ?value . }
    }
  }
}
