PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>

DELETE {
  GRAPH ?g {
    ?mandaat lmb:minAantalHouders ?oldmin.
    ?mandaat lmb:maxAantalHouders ?oldmax.
  }
  GRAPH <http://mu.semte.ch/graphs/temp/new-min-max> {
    ?mandaat lmb:minAantalHouders ?min.
    ?mandaat lmb:maxAantalHouders ?max.
  }
}
INSERT {
  GRAPH ?g {
    ?mandaat lmb:minAantalHouders ?min.
    ?mandaat lmb:maxAantalHouders ?max.
  }
}
WHERE {
  GRAPH ?g {
    ?mandaat a mandaat:Mandaat.
    OPTIONAL {
      ?mandaat lmb:minAantalHouders ?oldmin.
    }
    OPTIONAL {
      ?mandaat lmb:maxAantalHouders ?oldmax.
    }
  }
  GRAPH <http://mu.semte.ch/graphs/temp/new-min-max> {
    ?mandaat lmb:minAantalHouders ?min.
    ?mandaat lmb:maxAantalHouders ?max.
  }
}
