PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX conceptscheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?h {
    ?s a skos:Concept;
      skos:inScheme <http://publications.europa.eu/resource/authority/human-sex>;
      skos:topConceptOf <http://publications.europa.eu/resource/authority/human-sex>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a ext:GeslachtCode.
    BIND(?g as ?h). # Workaround to avoid Virtuoso SR002 22023 error
  }
}