PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX conceptscheme: <http://data.vlaanderen.be/id/conceptscheme/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT {
  GRAPH ?g {
    ?s a skos:Concept;
      skos:inScheme conceptscheme:BestuursorgaanClassificatieCode;
      skos:topConceptOf conceptscheme:BestuursorgaanClassificatieCode.
  }
}
WHERE {
  GRAPH ?g {
    ?s a ext:BestuursorgaanClassificatieCode;
  }
}