DELETE {
  GRAPH ?g {
    ?persoon ?p ?oOld.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/temp/verkiezingen-2024-zonder-strijd> {
    ?verkiezing a <http://data.vlaanderen.be/ns/mandaat#RechtstreekseVerkiezing>.
    ?verkiezing <http://data.vlaanderen.be/ns/mandaat#steltSamen> ?bestuursorgaan.
    ?lijst <http://data.vlaanderen.be/ns/mandaat#behoortTot> ?verkiezing.
    ?resultaat <http://data.vlaanderen.be/ns/mandaat#isResultaatVoor> ?lijst.
    ?resultaat <http://data.vlaanderen.be/ns/mandaat#isResultaatVan> ?persoon.
    ?persoon ?p ?o.
  }
  GRAPH ?g {
    ?bestuursorgaan <http://data.vlaanderen.be/ns/mandaat#isTijdspecialisatieVan> ?bestuursorgaanWithoutTime.
    ?persoon ?p ?oOld.
  }
}