PREFIX extlmb: <http://mu.semte.ch/vocabularies/ext/lmb/>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX generiek: <https://data.vlaanderen.be/ns/generiek#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX bestuursperiode: <http://data.lblod.info/id/concept/Bestuursperiode/>

INSERT {
  GRAPH ?g {
    ?bestuursorgaanIT a besluit:Bestuursorgaan ;
	    mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime ;
      mandaat:isTijdspecialisatieVan ?bestuursorgaan ;
      lmb:heeftBestuursperiode bestuursperiode:96efb929-5d83-48fa-bfbb-b98dfb1180c7 ;
      mu:uuid ?uuid ;
      org:hasPost ?mandaat .
    ?mandaat a mandaat:Mandaat ;
      mu:uuid ?mandaatUuid ;
      org:role ?role .
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/tmp> {
    ?bestuursorgaan a besluit:Bestuursorgaan .
    ?bestuursorgaanIT a besluit:Bestuursorgaan ;
	    mandaat:bindingStart "2025-01-01T00:00:00"^^xsd:dateTime ;
      # For some reason the wrong prefix is used here ... should be 
      # mandaat:isTijdspecialisatieVan ?bestuursorgaan .
      generiek:isTijdspecialisatieVan ?bestuursorgaan ;
      mu:uuid ?uuid .
    OPTIONAL {
      ?bestuurorgaanIT org:hasPost ?mandaat .
      ?mandaat a mandaat:Mandaat ;
        mu:uuid ?mandaatUuid ;
        org:role ?role .
    }
  }
  GRAPH ?g {
    ?bestuursorgaan a besluit:Bestuursorgaan .
  }
  FILTER (?g != <http://mu.semte.ch/graphs/tmp>)
}