PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
INSERT {
  GRAPH ?ocmwG {
    ?persoon ?p ?o.
  }
} WHERE {
  VALUES ?ocmwG {
    <http://mu.semte.ch/graphs/organizations/d7dd13304150f5fe65bd239093ef08dfae107864d26299ac91240a88782aed54/LoketLB-mandaatGebruiker> # Herstappe
    <http://mu.semte.ch/graphs/organizations/5bcbe1dcc6bd42354ce05e87c56a09a0e62c2fb67a4e6def59a30d40b1d70e4b/LoketLB-mandaatGebruiker> # Lo-Reninge
  }
  GRAPH ?ocmwG {
    ?verkiezing ext:copiedForOCMW ?ocmw.
    ?lijst mandaat:behoortTot ?verkiezing.
    ?res mandaat:isResultaatVoor ?lijst.
    ?res mandaat:isResultaatVan ?persoon.
  }
  ?persoon ?p ?o.
}