  PREFIX org: <http://www.w3.org/ns/org#>
  PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
  INSERT {
    GRAPH ?g {
      ?orgT org:hasPost ?mandaat.
      ?mandaat ?p ?o.
    }
  }WHERE {
    GRAPH ?g {
      ?orgT mandaat:isTijdspecialisatieVan ?org.
    }
    GRAPH <http://localhost/temp/politieraad> {
      ?orgT org:hasPost ?mandaat.
      ?mandaat ?p ?o.
    }
  }