(define-resource email ()
  :class (s-prefix "nmo:Email")
  :properties `((:message-id :string ,(s-prefix "nmo:messageId"));; e-mail protocol-specific id: https://tools.ietf.org/html/rfc2822#section-3.6.4
                (:from :string ,(s-prefix "nmo:messageFrom"))
                (:to :string ,(s-prefix "nmo:emailTo"))
                (:cc :string ,(s-prefix "nmo:emailCc"))
                (:bcc :string ,(s-prefix "nmo:emailBcc"))
                (:subject :string ,(s-prefix "nmo:messageSubject"))
                (:content :string ,(s-prefix "nmo:plainTextMessageContent"))
                (:html-content :string ,(s-prefix "nmo:htmlMessageContent"))
                (:is-read :boolean ,(s-prefix "nmo:isRead"))
                (:content-mime-type :string ,(s-prefix "nmo:contentMimeType"))
                (:received-date :datetime ,(s-prefix "nmo:receivedDate"))
                (:sent-date :datetime ,(s-prefix "nmo:sentDate"))
                (:number-of-retries :number ,(s-prefix "task:numberOfRetries")))
  :has-one `((email :via ,(s-prefix "nmo:inReplyTo")
                    :as "in-reply-to")
             (folder :via ,(s-prefix "nmo:isPartOf")
                                   :inverse t
                                   :as "folder"))
  :has-many `((email-header :via ,(s-prefix "nmo:messageHeader")
                    :as "headers")
              (file :via ,(s-prefix "nmo:hasAttachment")
                    :as "attachments"))
  ;           (email :via ,(s-prefix "nmo:references");;https://tools.ietf.org/html/rfc2822#section-3.6.4
  ;                   :as "references"))
  :resource-base (s-url "http://data.lblod.info/id/emails/")
  :features '(include-uri)
  :on-path "emails")
