(define-resource system-notification ()
  :class (s-prefix "ext:SystemNotification")
  :properties `(
    (:subject :string ,(s-prefix "dct:subject"))
    (:message :string ,(s-prefix "schema:description"))
    (:created-at :datetime ,(s-prefix "dct:created"))
    (:read-at :datetime ,(s-prefix "ext:readAt"))
    (:archived-at :datetime ,(s-prefix "ext:archivedAt"))
  )
  :has-one `((gebruiker :via ,(s-prefix "ext:notificationFor")
                        :as "gebruiker")
              (notification-code :via ,(s-prefix "dct:type")
                                   :as "code"))
  :has-many `((system-notification-links :via ,(s-prefix "ext:notificationLink")
                     :as "links"))
  :resource-base (s-url "http://data.lblod.info/id/SystemNotification")
  :features '(include-uri)
  :on-path "system-notifications")

(define-resource system-notification-link ()
  :class (s-prefix "ext:SystemNotificationLink")
  :properties `(
    (:type :string ,(s-prefix "ext:linkedType"))
    (:target :url ,(s-prefix "ext:linkedId"))
  )
  :has-one `((gebruiker :via ,(s-prefix "ext:notificationLink")
                        :inverse t
                        :as "notification"))
  :resource-base (s-url "http://data.lblod.info/id/SystemNotificationLink")
  :features '(include-uri)
  :on-path "system-notification-links")

  (define-resource notification-code ()
    :class (s-prefix "ext:SystemNotificationCode")
    :properties `((:label :string ,(s-prefix "skos:prefLabel")))
    :resource-base (s-url "http://data.lblod.info/id/concept/SystemNotificationCode/")
    :features '(include-uri)
    :on-path "system-notification-codes")
