CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  ?s ?p ?o .
  FILTER EXISTS {
    ?s a ?type .
    VALUES ?type {
      <http://purl.org/dc/terms/Agent>
    }
  }
  FILTER (?p NOT IN (<http://www.w3.org/ns/adms#identifier>, <http://www.w3.org/ns/org#classification>))
}