PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX lmb: <http://lblod.data.gift/vocabularies/lmb/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
  GRAPH ?graph {
    ?mandataris lmb:effectiefAt "2024-09-18T13:13:00.007Z"^^xsd:dateTime.
  }
}
WHERE {
  GRAPH ?graph {
    ?mandataris a mandaat:Mandataris;
      lmb:hasPublicationStatus <http://data.lblod.info/id/concept/MandatarisPublicationStatusCode/d3b12468-3720-4cb0-95b4-6aa2996ab188> . # Effectief mandataris-publication-status-code
  }
  FILTER NOT EXISTS {
    ?graph a <http://mu.semte.ch/vocabularies/ext/FormHistory>
  }
  FILTER NOT EXISTS {
    ?graph a <http://mu.semte.ch/graphs/public>
  }
}