prefix ext: <http://mu.semte.ch/vocabularies/ext/>
prefix besluit: <http://data.vlaanderen.be/ns/besluit#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix mu: <http://mu.semte.ch/vocabularies/core/>

insert {
  graph ?provincieLimburg {
    ?orgaanUri a besluit:Bestuursorgaan .
    ?orgaanUri mu:uuid ?uuid .
    ?orgaanUri skos:prefLabel ?orgaanLabel .
    ?orgaanUri besluit:classificatie ?orgaanType .
    ?orgaanUri besluit:bestuurt <http://data.lblod.info/id/bestuurseenheden/14278813524c762255aeba149e7d7134ddecfbb43e7d56910731bd4e13e34f39> .
  }
}
where {
  values ( ?uuid ?orgaanLabel ?orgaanType ) {
    ( "a6c3ffaf-1225-4b7c-8e2d-1d2194d3b73a"	"Hoog overlegcomité en afzonderlijk bijzonder comité van het gesubsidieerd personeel van het provinciaal onderwijs"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/4af47caf-009d-44eb-acf0-b87877af7bb3> )
    ( "1835a5be-1e2e-482c-a862-dea838c60115"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/4af47caf-009d-44eb-acf0-b87877af7bb3> )
    ( "f9416c33-db1d-43ed-92e1-39c30ba87444"	"Euregio Maas-Rijn"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "e7c78944-9f73-4478-acb2-d7746eb9cd0c"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "ad01f23f-cf8d-45f1-9524-1c81986d4bd6"	"Euregio Maas-Rijn - Bestuur"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "9d700765-1595-472e-bc48-fd3031da9c31"	"Vereniging van de Vlaamse Provincies (VVP) - Bestuur"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "f2882eb3-1913-45f7-962c-7600b2efd245"	"Erkend Regionaal Samenwerkingsverband Limburg (ERSV Limburg) (in vereffening)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "0c5e9f69-a54e-4f0d-8103-3aafb6a81fd7"	"Limburg Sterk Merk (LSM)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "a83e6b5a-9cfb-4fa9-ab25-86b119de9e39"	"s-Lim"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "31f38242-f09a-4901-8818-70d435563034"	"Provinciale Ontwikkelingsmaatschappij Limburg (POM Limburg)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "db9eefdb-7ddd-4621-87ea-6953aa9343a7"	"Vlaamse Maatschappij voor Watervoorziening (De Watergroep)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "06459ee6-aa56-4e50-bd5a-2abb7c7e0e0f"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/013cc838-173a-4657-b1ae-b00c048df943> )
    ( "c7c657f8-07a1-4871-b4bc-c6521e17e075"	"Erkend Regionaal Samenwerkingsverband Limburg (ERSV Limburg) (in vereffening) - Regionaal Sociaal-Economisch Overlegcomité (RESOC)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "596485a7-ff39-4560-b458-26c107014f86"	"Vereniging van de Vlaamse Provincies (VVP) - Regionaal Sociaal-Economisch Overlegcomité (RESOC)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "8a98396f-abbc-43b9-9d26-01f5ecbd0ee8"	"Limburgse Economische Raad (L.E.R.)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "f8f1c441-c28c-46c9-a46c-bd5f36190807"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "38f8ad07-1bae-4533-b9dc-1b50798f02bb"	"Toerisme Limburg"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "95077846-87ea-4f88-922e-f1f725fb515a"	"EthiasCo"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "95caaf66-36bd-4a1b-b2ad-326551caa664"	"Vlaams Coördinatiecentrum Mestverwerking (VCM)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/b52094ff-21a2-4da8-8dbe-f513365d1528> )
    ( "2572fa90-0ba0-4d81-9846-20fd358d9f08"	"Provinciale Ontwikkelingsmaatschappij Limburg (POM Limburg)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> )
    ( "03d0ec1b-4d19-452b-9198-567fbac576b3"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.vlaanderen.be/id/concept/BestuursorgaanClassificatieCode/5733254e-73ff-4844-8d43-7afb7ec726e8> )
    ( "fca6d1f7-a132-412a-9d6b-ff1b39d5aa76"	"Samenwerking Grensgebied de Kempen - Bestuurlijk overleg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "424f7100-b2e6-4339-9378-6a0da55b535d"	"Vereniging van de Vlaamse Provincies (VVP) - Bestuurlijk overleg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "97fa1c25-d0a0-41e2-b18c-4af06458ec86"	"Vervoerregio Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/79b34b2f-5bc5-4939-900b-3db7fc3e1ef3> )
    ( "1083d8a7-9aba-4f8c-810a-9c1f356e338b"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/79b34b2f-5bc5-4939-900b-3db7fc3e1ef3> )
    ( "6b5554be-e1d7-4049-bcdc-30bec1bbb5b3"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/7f7f4e20-ff35-4f26-91f5-a7faaf8f59aa> )
    ( "ac54d93a-7917-4dd8-beb3-9f3cc03fe516"	"Vereniging van de Vlaamse Provincies (VVP) - Comité van afgevaardigden van de inrichtende machten (CAIM)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "2ed898ee-a4e5-46fc-a3cb-0053f7b3c5d1"	"Vereniging van de Vlaamse Provincies (VVP) - Beheerscomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "bf7a8f5f-f84a-444b-adde-36c08e569c21"	"Vereniging van de Vlaamse Provincies (VVP) - Plaatselijke Groep"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "5ba4aa6d-6a0a-4a21-b1de-e95b6ec3239f"	"Vereniging van de Vlaamse Provincies (VVP) - Leadercomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "e656a399-beb1-44bc-a47d-afc7f4943cb9"	"Vereniging van de Vlaamse Provincies (VVP) - Samenstelling"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "5d726ed7-0a7b-46a8-8eea-78f3d1d93be5"	"Vereniging van de Vlaamse Provincies (VVP) - Aandeelhoudersbestuur van de drinkwaterdienst"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "2e132a12-898a-4a41-ae8e-8666c0fd68ad"	"Vereniging van de Vlaamse Provincies (VVP) - Grindcomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "64df6e60-3208-4093-99b4-6e34588b2aa7"	"Vereniging van de Vlaamse Provincies (VVP) - Technische Werkgroep"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "8de5c024-6a1a-4eec-a52f-61df21108940"	"Vereniging van de Vlaamse Provincies (VVP) - Gezamenlijke vergaderingen van de inrichtende macht en de schoolraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "60174862-706c-4088-8e4c-110c899f4014"	"Vereniging van de Vlaamse Provincies (VVP) - Gezamenlijke vergadering van de inrichtende macht en de schoolraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "c9d58850-b09f-4bb2-8bc0-83cf983eb8fe"	"Vereniging van de Vlaamse Provincies (VVP) - Centrumraad centrum deeltijds beroepssecundair onderwijs"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "7b85b4d8-da12-462c-b487-daf93fc6a8e3"	"Vereniging van de Vlaamse Provincies (VVP) - Provinciaal Managementcomité (PMC)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "b666cee4-154b-4323-becc-d754fcab4774"	"Vereniging van de Vlaamse Provincies (VVP) - Beperkt Provinciaal Managementcomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "727a1307-e16e-4568-94af-05ebf06ce5dd"	"Vereniging van de Vlaamse Provincies (VVP) - Afzonderlijk bijzonder comité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "71766eac-86a4-43bf-8c9d-aba020fae938"	"Vereniging van de Vlaamse Provincies (VVP) - Comité van Toezicht"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "4b0db818-307d-40c2-bdd6-930d7f8e311f"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/298234f3-b012-47b8-8779-9b887e55861d> )
    ( "3679edad-6043-4c5c-b925-6be23a5cee0e"	"Vereniging van de Vlaamse Provincies (VVP) - Opvolgingscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "76fd2117-c5c7-4988-9d30-2347d902b742"	"Vereniging van de Vlaamse Provincies (VVP) - Centrumraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "8f6b0431-ca47-46a2-8a6f-e22f1ff80bf4"	"Vereniging van de Vlaamse Provincies (VVP) - Bestuursorgaan"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "f5a46d5d-9b30-4f33-831f-9e73df21cc6f"	"Vereniging van de Vlaamse Provincies (VVP) - Wetenschappelijke begeleidingscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "c18c4828-cb1c-4468-9e15-94402078af19"	"Vereniging van de Vlaamse Provincies (VVP) - Programmateam"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "2b4fc46c-d91f-4e00-b814-040fd9646ea4"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/39574cb9-0ca4-49da-82c5-468ebf1f5f50> )
    ( "9d04cfc3-08a4-4274-ac42-8c3f498006ae"	"Vereniging van de Vlaamse Provincies (VVP) - Beheerscomité - Plaatselijke groep"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "7971f41b-0cb7-4755-8c86-368c6c3fadd4"	"Vereniging van de Vlaamse Provincies (VVP) - Raad van Advies"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "07c3223c-426d-4974-869c-f16638811d31"	"Vereniging van de Vlaamse Provincies (VVP) - College van Vereffenaars"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "ac3f3ca3-b158-4d38-8bd7-13817c7ceea5"	"Vereniging van de Vlaamse Provincies (VVP) - College van vereffenaars"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "d48d17d9-6413-430f-97e6-7eb59ba16b02"	"Vereniging van de Vlaamse Provincies (VVP) - Bestuurscomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "1bb0faf4-bd9d-4eae-ba4c-ff3ca5a375c4"	"Vereniging van de Vlaamse Provincies (VVP) - Raad van Toezicht"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "35b1537e-5d25-4139-9064-0f85833ce4d3"	"Vereniging van de Vlaamse Provincies (VVP) - (Raad van Bestuur) vervangen door vereffenaar"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "38edfdd8-5967-41f7-a549-8ae33a61ad33"	"Vereniging van de Vlaamse Provincies (VVP) - Dagelijks Bestuur"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "ff9112ea-93b9-433a-bce5-041786a3e960"	"Vereniging van de Vlaamse Provincies (VVP) - Commissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "1e7b54fd-82f4-4c14-8d53-7893d0745e86"	"Vereniging van de Vlaamse Provincies (VVP) - Toezichtscomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "eb49d77e-5800-43c8-945c-ffff23f7ff5b"	"Vereniging van de Vlaamse Provincies (VVP) - Coördinatorenoverleg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "77d05a09-5083-4e9c-a356-028cf1294671"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/ac9c0cec-aad2-4ff7-9335-43eb59cdbf17> )
    ( "8b20c08b-af9d-4ff5-9298-506d6a31e1a0"	"Vereniging van de Vlaamse Provincies (VVP) - Vast Bureau"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "9e672d08-17d6-4e94-9a4e-df4da48c0b04"	"Vereniging van de Vlaamse Provincies (VVP) - Bestuurscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "04171dec-ece6-412c-a60a-9f869b1b4105"	"Vereniging van de Vlaamse Provincies (VVP) - Bemiddelingscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "1deb7544-f40b-4201-a69c-74a38263f243"	"Vereniging van de Vlaamse Provincies (VVP) - Interne Beroepscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "fe23e867-1d15-45bf-b567-08d2d75af7fd"	"Vereniging van de Vlaamse Provincies (VVP) - Interne beroepscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "f18bc31f-211d-4680-8f98-60eaa295bf17"	"Vereniging van de Vlaamse Provincies (VVP) - Managementcomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "bd757ad6-f4d0-441b-8690-fb00f109c7cb"	"Vereniging van de Vlaamse Provincies (VVP) - Adviesraad Streekgericht Bibliotheekbeleid"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "1868362e-e3d9-400e-828c-d4591dc16fcd"	"Vereniging van de Vlaamse Provincies (VVP) - Adviesraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "f5da470b-c2e2-4424-83fb-2c282cd71c8f"	"Vereniging van de Vlaamse Provincies (VVP) - Euregionale Sociaal-Economische Raad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "d7ff0826-6799-49ec-868f-6c25c0735285"	"Vereniging van de Vlaamse Provincies (VVP) - Euregioraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "71b10590-acff-497b-8f9d-093a1a28a572"	"Vereniging van de Vlaamse Provincies (VVP) - Raad van Beheer"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "86a8a1f8-28b9-4fe6-92d3-ddd3e57f7d40"	"Vereniging van de Vlaamse Provincies (VVP) - Raadgevend Comité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "1f575338-99d4-49ba-b723-8abf011bcf91"	"Vereniging van de Vlaamse Provincies (VVP) - Provinciaal Comité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "0444d51d-523c-456f-84e5-db380dbd9f33"	"Vereniging van de Vlaamse Provincies (VVP) - Sectorcomité Oost-Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "14070dbf-dd66-4709-81c8-8c279ed5aa71"	"Vereniging van de Vlaamse Provincies (VVP) - Sectorcomité Zuidoost-Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "6bccf2e9-dd14-4b88-8f2f-8afda12e817e"	"Vereniging van de Vlaamse Provincies (VVP) - Sectorcomité Noord-Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "a8e9bb1f-0dd9-4b7f-a205-fc90b2198998"	"Vereniging van de Vlaamse Provincies (VVP) - Sectorcomité Zuidwest-Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "d5780f91-5638-4ee1-8f21-ff0a41b70ac1"	"Vereniging van de Vlaamse Provincies (VVP) - Sectorcomité West-Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "2bdc02b1-830a-4da0-86c4-16e6fb51def6"	"Vereniging van de Vlaamse Provincies (VVP) - College van Commissarissen"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "dabacce3-9357-4c7e-af40-914269feae27"	"Vereniging van de Vlaamse Provincies (VVP) - gemeenschappelijke vergaderingen van het bestuur van de scholengemeenschap met het medeze"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "a4b39229-8c72-482e-a937-42852040f456"	"Vereniging van de Vlaamse Provincies (VVP) - Bibliotheekraad"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "a276ce05-cc17-48a2-8d1e-975a269c3895"	"Vereniging van de Vlaamse Provincies (VVP) - Beleidscommissie"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "e017131f-ae48-46c8-b7a0-f1b430d0fe68"	"Vereniging van de Vlaamse Provincies (VVP) - College van Beleidsdeskundigen"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "af620e1a-7558-4d45-82da-0276dd2959cf"	"Vereniging van de Vlaamse Provincies (VVP) - TaskForce Limburg"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "96029358-07bf-4581-82b7-187dbf1352ce"	"Vereniging van de Vlaamse Provincies (VVP) - college van vereffenaars"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "81325592-a4e7-4e0a-ac39-93af358923ef"	"Vereniging van de Vlaamse Provincies (VVP) - Vereffenaar"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "bd7e9428-5e97-4dad-999c-f6de5fee98d1"	"Vereniging van de Vlaamse Provincies (VVP) - vereffenaar"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "c27c9cca-3506-4aa4-a416-23fe1f9ba85d"	"Vereniging van de Vlaamse Provincies (VVP) - Vlaams Managementcomité"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
    ( "762bda11-a9a8-4bba-8aff-389494e1482c"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/0ee41ca8-76b4-4c98-9b61-ca746b66d7c2> )
    ( "d3e4e535-6bad-4d04-904b-d10f1ffdb869"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/4af47caf-009d-44eb-acf0-b87877af7bb3> )
    ( "fbe38db3-8714-4c7c-95c4-6b95ea467c91"	"Vereniging van de Vlaamse Provincies (VVP)"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/f3ebb3a5-023c-4e68-b039-8f62235c7a25> )
    ( "f93a712a-acad-4bbd-8c3b-fad4cd45d1bc"	"Vereniging van de Vlaamse Provincies (VVP) - Client Board"	<http://data.lblod.info/id/lb-orgaan-classificatiecode/aa5f804a-2ad0-422d-9569-ea93496f5b69> )
  }
  bind(uri(concat("http://data.lblod.info/id/bestuursorganen/", ?uuid)) as ?orgaanUri).
  ?provincieLimburg ext:ownedBy <http://data.lblod.info/id/bestuurseenheden/14278813524c762255aeba149e7d7134ddecfbb43e7d56910731bd4e13e34f39> .
}
