DELETE {
  GRAPH ?g {
    ?s <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?persoon.
  }
}
WHERE {
  GRAPH ?g {
    ?s <http://data.vlaanderen.be/ns/mandaat#isBestuurlijkeAliasVan> ?persoon.
  }
  ?persoon a <http://www.w3.org/ns/activitystreams#Tombstone> .
}