PREFIX orgaancode: <http://data.lblod.info/id/lb-orgaan-classificatiecode/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX cs: <http://data.lblod.info/id/conceptscheme/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX code: <http://data.lblod.info/id/lb-mandaat-classificatiecode/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>


INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    code:c724b7a2-012e-4acd-863c-f98c97a9ba56 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "c724b7a2-012e-4acd-863c-f98c97a9ba56" ;
        skos:prefLabel "Adviserend lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:82eb2bc7-09c4-43f8-9d9f-841243eb1f6a a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "82eb2bc7-09c4-43f8-9d9f-841243eb1f6a" ;
        skos:prefLabel "Adviserend lid met raadgevende stem" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:3de1400b-c42b-4a26-9c86-10bb529b593e a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "3de1400b-c42b-4a26-9c86-10bb529b593e" ;
        skos:prefLabel "Adviserend lid middenveld" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:0cdffd2e-0225-4244-98fd-e4767c98078d a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "0cdffd2e-0225-4244-98fd-e4767c98078d" ;
        skos:prefLabel "Adviserend lid zonder stemrecht" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:e8a215a6-0c1f-491a-8cc3-6ab8fe1e73e9 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "e8a215a6-0c1f-491a-8cc3-6ab8fe1e73e9" ;
        skos:prefLabel "Adviserend vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:c09cf783-0356-4cd8-92ef-5b6c560962e5 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "c09cf783-0356-4cd8-92ef-5b6c560962e5" ;
        skos:prefLabel "Ambtelijk plaatsvervanger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:d7d374ee-74c9-4792-9a96-2ed166c50274 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "d7d374ee-74c9-4792-9a96-2ed166c50274" ;
        skos:prefLabel "Ambtelijke plaatsvervangend vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:661b0fbf-7284-4ec1-9d13-8d855af532aa a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "661b0fbf-7284-4ec1-9d13-8d855af532aa" ;
        skos:prefLabel "Ambtelijke vaste vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:b626fb85-52df-4a03-9455-c28315e9a116 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "b626fb85-52df-4a03-9455-c28315e9a116" ;
        skos:prefLabel "Eerste plaatsvervanger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:15b60a6e-7c9e-4afc-97f1-80784f105fae a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "15b60a6e-7c9e-4afc-97f1-80784f105fae" ;
        skos:prefLabel "Effectief lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:0f8eef4e-7470-4f7d-9f09-4fad8a42fd08 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "0f8eef4e-7470-4f7d-9f09-4fad8a42fd08" ;
        skos:prefLabel "Effectieve vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:3b483f29-306a-4b68-997c-15cb32bb072b a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "3b483f29-306a-4b68-997c-15cb32bb072b" ;
        skos:prefLabel "Kandidaat-bestuurder" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:ec29066b-1fba-4e2c-ad11-f1f73a891a6e a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "ec29066b-1fba-4e2c-ad11-f1f73a891a6e" ;
        skos:prefLabel "Lid (aangelegenheden PBW)" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:55061e48-0fa6-46da-94d6-099f15f94974 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "55061e48-0fa6-46da-94d6-099f15f94974" ;
        skos:prefLabel "Lid als lid RESOC" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:4fd2a8bb-a828-4153-bf3f-9561188d35c0 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "4fd2a8bb-a828-4153-bf3f-9561188d35c0" ;
        skos:prefLabel "Lid dienst Landbouw en Platteland" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:215d60cb-7993-4cdb-8c37-0564a19b6915 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "215d60cb-7993-4cdb-8c37-0564a19b6915" ;
        skos:prefLabel "Lid komende uit of bekend met de kunstensector" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:31217a76-f3ca-4dc7-a4a6-a4247722bab6 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "31217a76-f3ca-4dc7-a4a6-a4247722bab6" ;
        skos:prefLabel "Lid middenveld" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:1b1b373b-ceb9-4d20-9bba-24a71ff6c62b a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "1b1b373b-ceb9-4d20-9bba-24a71ff6c62b" ;
        skos:prefLabel "Lid provinciale organisatie" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:fb900a61-4ceb-4c3e-9100-535a89ec3d43 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "fb900a61-4ceb-4c3e-9100-535a89ec3d43" ;
        skos:prefLabel "Lid publieke sector" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:b4221dda-b91f-4069-a009-6152d6e0517b a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "b4221dda-b91f-4069-a009-6152d6e0517b" ;
        skos:prefLabel "Lid werkgevers/middenstands/landbouworganisaties SERV" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:23879068-96b3-46ad-b051-177346b3e58f a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "23879068-96b3-46ad-b051-177346b3e58f" ;
        skos:prefLabel "Lid werknemersorganisaties SERV" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:cc51d9f0-ddca-45f3-ab38-0f021eada23b a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "cc51d9f0-ddca-45f3-ab38-0f021eada23b" ;
        skos:prefLabel "Lid-waarnemer" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:91576147-c1a7-4309-ad56-891015c20535 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "91576147-c1a7-4309-ad56-891015c20535" ;
        skos:prefLabel "Niet-stemgerechtigd lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:9f4dbcea-f543-4b63-8b23-b5d543933ee1 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "9f4dbcea-f543-4b63-8b23-b5d543933ee1" ;
        skos:prefLabel "Ondervoorzitter" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:1e0c280e-32b1-4a3e-9abd-d2290cce00ef a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "1e0c280e-32b1-4a3e-9abd-d2290cce00ef" ;
        skos:prefLabel "Plaatsvervangend adviserend lid middenveld" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:9523b180-c2fa-47ef-a8c2-100c171e831c a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "9523b180-c2fa-47ef-a8c2-100c171e831c" ;
        skos:prefLabel "Plaatsvervangend lid dienst Landbouw en Platteland" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:943e70a3-b68a-440b-a269-0e66ea73c070 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "943e70a3-b68a-440b-a269-0e66ea73c070" ;
        skos:prefLabel "Plaatsvervangend lid middenveld" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:90f7043b-98db-49d6-bf34-d26668c6631c a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "90f7043b-98db-49d6-bf34-d26668c6631c" ;
        skos:prefLabel "Plaatsvervangend lid provinciale organisatie" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:534532bc-7c0d-4257-a0c3-354c31f1f419 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "534532bc-7c0d-4257-a0c3-354c31f1f419" ;
        skos:prefLabel "Plaatsvervangend stemgerechtigd lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:7880bbf9-5424-474a-af91-75c831e7aa5d a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "7880bbf9-5424-474a-af91-75c831e7aa5d" ;
        skos:prefLabel "Plaatsvervangend stemgerechtigde vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:fd0f605f-d8c5-4a37-946c-787122f97a94 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "fd0f605f-d8c5-4a37-946c-787122f97a94" ;
        skos:prefLabel "Plaatsvervangend adviserend lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:9e8110c8-7c98-42ad-ab96-6cc33cfd10cd a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "9e8110c8-7c98-42ad-ab96-6cc33cfd10cd" ;
        skos:prefLabel "Plaatsvervangend lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:176c7cba-8ae8-4236-a2df-6b002817d63e a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "176c7cba-8ae8-4236-a2df-6b002817d63e" ;
        skos:prefLabel "Plaatsvervangend secretaris" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:56486dc8-1d77-44a3-9d2d-14dc335fe719 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "56486dc8-1d77-44a3-9d2d-14dc335fe719" ;
        skos:prefLabel "Plaatsvervangend vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:10389c0b-591c-49b7-b358-479f6d5c4df4 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "10389c0b-591c-49b7-b358-479f6d5c4df4" ;
        skos:prefLabel "Politieke plaatsvervangende vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:ba05738e-9233-4e95-b2e0-6eb81ae9ce03 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "ba05738e-9233-4e95-b2e0-6eb81ae9ce03" ;
        skos:prefLabel "Politieke vaste vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:a2535c60-5b42-4622-b07e-fe8c9b6c8c04 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "a2535c60-5b42-4622-b07e-fe8c9b6c8c04" ;
        skos:prefLabel "Raadgevend lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:c5506328-6187-4986-960c-38f87fe9fa7d a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "c5506328-6187-4986-960c-38f87fe9fa7d" ;
        skos:prefLabel "Secretaris" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:4e6b1a7e-fe0c-45f5-ac1c-b562dd90044e a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "4e6b1a7e-fe0c-45f5-ac1c-b562dd90044e" ;
        skos:prefLabel "Stemgerechtigd lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:05c60352-ecb2-484f-a555-b9d700b0f428 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "05c60352-ecb2-484f-a555-b9d700b0f428" ;
        skos:prefLabel "Stemgerechtigd lid onderwijs" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:3c0175d9-6f27-40e8-a02a-5b810f48404c a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "3c0175d9-6f27-40e8-a02a-5b810f48404c" ;
        skos:prefLabel "Stemgerechtigd lid socio-economische organisatie" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:c321ef6c-f7ec-43ad-b14b-efddd08daeb0 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "c321ef6c-f7ec-43ad-b14b-efddd08daeb0" ;
        skos:prefLabel "Stemgerechtigd vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:ff45ee78-a4d5-4dbd-94b3-62714f1e3215 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "ff45ee78-a4d5-4dbd-94b3-62714f1e3215" ;
        skos:prefLabel "Technicus" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:caf93096-5806-4806-80fa-14680683716a a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "caf93096-5806-4806-80fa-14680683716a" ;
        skos:prefLabel "Tweede plaatsvervanger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:eaa21c78-661e-44bd-9710-452159a4b39c a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "eaa21c78-661e-44bd-9710-452159a4b39c" ;
        skos:prefLabel "Vaste vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:f54b8de5-c6f0-4c11-b221-4766c9450f88 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "f54b8de5-c6f0-4c11-b221-4766c9450f88" ;
        skos:prefLabel "Vertegenwoordiger" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:20f0a2a3-1785-4346-898a-14789a5682cc a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "20f0a2a3-1785-4346-898a-14789a5682cc" ;
        skos:prefLabel "Vicevoorzitter" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:27ea7ccb-ecc7-4e6b-b190-208addb2cc4f a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "27ea7ccb-ecc7-4e6b-b190-208addb2cc4f" ;
        skos:prefLabel "Waarnemer" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .

    code:5ae0b70e-3845-4a82-88cd-f6c8051e6f68 a skos:Concept, ext:BestuursfunctieCode ;
        mu:uuid "5ae0b70e-3845-4a82-88cd-f6c8051e6f68" ;
        skos:prefLabel "Werkend lid" ;
        skos:inScheme cs:LokaalMandaatClassificatieCode ;
        skos:topConceptOf cs:LokaalMandaatClassificatieCode .
  }
}
